### PR TITLE
Show excerpt on index

### PR DESCRIPTION
**Pull request by jingsong-liu**
Index which is full of long posts makes reader hard to glance of your site. So I think it is better to show post's header/meta and excerpt .

this pull request is only for reference ：）

### CODE REVIEW

**Comment by somospolvo** [comment]
Me parece excelente, aunque de todas maneras el texto es algo corto (por lo cual no queda muy estetico). Yo he optado por eliminar esta parte:

```
<section class="post-content">
{{content}}
</section>
```

¿Creen que eso me puede traer problemas de SEO? ¿creen que se pueda modificar la plantilla para que simplemente reconozca la etiqueta `<!-- more -->` y no muestre lo que viene después de ella?

**Comment by nehalist** [comment]
@somospolvo Uhm, sorry, I have no idea what you're talking about since I don't speak your language :/

**Comment by nehalist** [comment]
@jeesyn I'm not entirely sure about this; I always liked the "no excerpt" style. This is probably preference-based. But I'll take a look at it and see if it fits. Maybe my preferences are just not cool :P 

(reason for opening and re-opening is because I'm really bad at clicking at this time...)

**Comment by jingsong-liu** [comment]
Well, it's truely a preference-based advice. You may keep your style or just provide an option to configure the style.

**Pull request closed without merging**
